Repository inngest/website, pull requests merged in 2024-07, with the labels that each got.

#860 Add reference docs for `onFunctionRun.finished` hook in TS middleware
  pages/docs/reference/middleware/lifecycle.mdx
Labels: documentation

#861 Add reference docs for sending events to a particular environment
  pages/docs/reference/events/send.mdx
Labels: documentation

#864 fix(docs): ensure Python SDK deeply nested menu items stay visible when active
  shared/Docs/Navigation.tsx
Labels: bug, documentation

#869 feat(blog): "Announcing: Batch Keys"
  pages/blog/_posts/announcing-batch-keys.mdx
  public/assets/blog/announcing-batch-keys/batch-keys-1.jpg
  public/assets/blog/announcing-batch-keys/batch-keys-2.jpg
  public/assets/blog/announcing-batch-keys/featured-image.png
Labels: blog post

#870 Update Cloudflare AI usage example; lib now deprecated
  pages/docs/reference/middleware/examples.mdx
Labels: documentation

#872 fix(docs): missing docs for `idempotency` on Python SDK
  pages/docs/reference/python/functions/create.mdx
Labels: documentation

#873 Add note for runtime environment variables if needed in a framework
  pages/docs/sdk/environment-variables.mdx
Labels: documentation
